<?php

$HT = [
    'pageadmin_choose_pagegroup' => 'Page group:',
    'pageadmin_choose_page' => 'Please choose page to edit:',
    'pageadmin_choose_submit' => 'Weiter',
    'pageadmin_choose_add' => '[Seite hinzufügen]',

    'pageadmin_add_pagekey' => 'Seitenschlüssel:',
    'pageadmin_add_pagekey_tooltip' => 'Bitte geben Sie den kompletten Pfad an,&#xa;z.B.: /thema/artikel.html&#xa;Wenn als Dateiname index.html verwendet wird,&#xa;dann wird diese Seite automatisch geladen,&#xa;wenn beim Seitenaufruf nur ein Verzeichnis&#xa;angegeben wird, z.B.: /thema/',
    'pageadmin_add_submit' => 'Anlegen',
    'pageadmin_add_error_reservedpath' => 'Der von Ihnen gewählte Schlüssel ist für das System reserviert, er darf nicht mit "/_" beginnen.',
    'pageadmin_add_error_keytooshort' => 'Bitte verwenden Sie mindestens 4 Zeichen für den Seitenschlüssel.',
    'pageadmin_add_error_keyalreadyinuse' => 'Dieser Seitenschlüssel ist bereits vergeben.',

    'pageadmin_edit_currentpage' => 'Aktuelle Seite:',
    'pageadmin_edit_changescommitted' => 'Änderungen gespeichert:',
    'pageadmin_edit_languagespecific' => 'Sprachspezifisch',
    'pageadmin_edit_pagecontent' => 'Seiteninhalt',
    'pageadmin_edit_pagecontent_tooltip' => 'HTML Quelltext, unsichere Tags werden herausgefiltert.',
    'pageadmin_edit_pagetitle' => 'Seitentitel:',
    'pageadmin_edit_pagetitle_tooltip' => 'Reiner Text, erscheint im Browser als Titel der Seite.&#xa;Wenn dieses Feld leer gelassen wird, wird der&#xa;Standardseitentitel verwendet.',
    'pageadmin_edit_metadescription' => 'Meta-Description:',
    'pageadmin_edit_metadescription_tooltip' => 'Reiner Text, eine kurze Zusammenfassung der Seite.',
    'pageadmin_edit_metakeywords' => 'Meta-Keywords:',
    'pageadmin_edit_metakeywords_tooltip' => 'Reiner Text, Schlüsselwörter, durch die diese&#xa;Seite bei Suchmaschinen gefunden werden soll.',
    'pagedamin_edit_nolanguagespecificdataexists' => 'In dieser Sprache sind noch keine Texte angelegt. Klicken Sie hier um dies zu tun',
    'pageadmin_edit_basedata' => 'Sprachunabhängig',
    'pageadmin_edit_pagetype' => 'Page type:',
    'pageadmin_edit_pagetype_tooltip' => 'Welche Seitenvorlage soll verwendet werden?&#xa;content: standardlayout&#xa;contentnosubnav: Standardlayout ohne Subnavigation&#xa;itemoverview: Artikelübersichtsseite&#xa;itemoverviewgrpd: Artikelübersichtsseite mit Gruppierung der Artikel&#xa;shorturl: Diese Seite soll den Besucher auf die in Page config angegebene Seite umleiten.',
    'pageadmin_edit_pagegroup' => 'Page group:',
    'pageadmin_edit_pagegroup_tooltip' => 'In welcher Kategorie soll diese Seite in der Seitenverwaltung gruppiert werden?',
    'pageadmin_edit_pageconfig' => 'Page config:',
    'pageadmin_edit_pageconfig_tooltip' => 'Beim Seitentyp shorturl, hier das Ziel der Weiterleitung angeben, z.B.: http://www.haase-it.com/&#xa;Beim allen anderen Seitentypen ein valides JSON Objekt mit Seitenspezifischen Daten.&#xa;Beim Seitentyp itemoverview/itemoverviewgrpd hier den Artikelindex angeben:&#xa;{&#34;itemindex&#34;:&#34;A01&#34;} oder {&#34;itemindex&#34;:[&#34;A01&#34;, &#34;A02&#34;]}',
    'pageadmin_edit_subnavarea' => 'Page Subnavarea:',
    'pageadmin_edit_subnavarea_tooltip' => 'Welche Subnavigation soll auf dieser Seite eingeblendet werden?',
    'pageadmin_edit_submit' => 'Submit',
    'pageadmin_edit_deletetitle' => 'Seite löschen',
    'pageadmin_edit_deleteconfirm' => 'Ich möchte diese Seite in allen Sprachen löschen',
    'pageadmin_edit_deletesubmit' => 'Löschen',
    'pageadmin_deleted' => 'Die Seite wurde gelöscht.',
];
